// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdQ5khdvym4lpWwOi_HxLBCCiuMNddJM8',
    appId: '1:161264919588:web:8f330119c6c51212a264b1',
    messagingSenderId: '161264919588',
    projectId: 'authentication-in-flutte-b2567',
    authDomain: 'authentication-in-flutte-b2567.firebaseapp.com',
    storageBucket: 'authentication-in-flutte-b2567.firebasestorage.app',
    measurementId: 'G-MZ5RC3G9ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkgI7F9N6tFPFENXqqbm2nx8q_okgqM2k',
    appId: '1:161264919588:android:a857ed69ae9bce1ca264b1',
    messagingSenderId: '161264919588',
    projectId: 'authentication-in-flutte-b2567',
    storageBucket: 'authentication-in-flutte-b2567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgqx-CwsGJRz48XWUSERqXp-bhElvNiJA',
    appId: '1:161264919588:ios:63964ffdad5f2a66a264b1',
    messagingSenderId: '161264919588',
    projectId: 'authentication-in-flutte-b2567',
    storageBucket: 'authentication-in-flutte-b2567.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgqx-CwsGJRz48XWUSERqXp-bhElvNiJA',
    appId: '1:161264919588:ios:63964ffdad5f2a66a264b1',
    messagingSenderId: '161264919588',
    projectId: 'authentication-in-flutte-b2567',
    storageBucket: 'authentication-in-flutte-b2567.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdQ5khdvym4lpWwOi_HxLBCCiuMNddJM8',
    appId: '1:161264919588:web:cd4264898fd4ea87a264b1',
    messagingSenderId: '161264919588',
    projectId: 'authentication-in-flutte-b2567',
    authDomain: 'authentication-in-flutte-b2567.firebaseapp.com',
    storageBucket: 'authentication-in-flutte-b2567.firebasestorage.app',
    measurementId: 'G-LLVTBPBLLL',
  );

}